<?php

/**
 * @file
 * Imagefield Zoom module.
 */

/**
 * Implementation of hook_theme().
 */
function waxo_imagefield_zoom_theme() {
  return [
    'waxo_imagefield_zoom' => [
      'variables' => [
        'images' => NULL,
      ],
      'template' => 'imagefield-zoom',
    ],
  ];
}

/**
 * Implements template_preprocess_imagefield_zoom().
 *
 * @param mixed $variables
 *    Variables storage.
 */
function template_preprocess_waxo_imagefield_zoom(&$variables) {
  $variables['#attached']['library'][] = 'waxo_imagefield_zoom/zoom';
}
