<?php

/**
 * @file
 * Custom code for custom Jeff Wax blocks.
 */

/**
 * Implements hook_theme().
 */
function waxo_blocks($existing, $type, $theme, $path) {
  return [
    'waxo_blocks_title_block' => [
      'variables' => [
        'title' => NULL,
        'classes' => [],
        'tag' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function waxo_blocks_preprocess_block(&$variables) {

  if (isset($variables['content']['#block_content'])) {
    // Make sure our custom CSS is loaded to take advantage of custom CSS.
    $variables['#attached']['library'][] = 'waxo_blocks/waxo_blocks';
  }
}
